#!/usr/bin/env bash
#  script extends previous exercise command and displays line containing the bash word, this allowing you to easily get the PID of your Bash process
# Don't use pgrep
# The shellcheck disable=SC2009

./1-list_your_processes | grep "bash"
